import type * as faceapi from 'face-api.js';

export interface PhotoFile {
  id: string;
  name: string;  // original filename, copied from file.name at upload time
  file: File;
  url: string;
}

export interface FaceDetectionResult {
  landmarks: faceapi.FaceLandmarks68;
  expressions: faceapi.FaceExpressions;
  detection: faceapi.FaceDetection;
}

export interface PhotoAnalysis {
  photoId: string;
  lighting: number;
  sharpness: number;
  faces: FaceDetectionResult[];
  eyesOpen: number;
  smiles: number;
  composition: number;
  instagram: number;
  overallScore: number;    // equal-weight average across all scores, computed by analyzePhoto.ts
  tags: string[];
  reasoning: string;
}

export interface SelectedCriteria {
  eyesOpen: boolean;
  allEyesOpen: boolean;
  bestSmiles: boolean;
  specificPeople: boolean;
  specificPeopleNames: string;
  bestLighting: boolean;
  leastBlurry: boolean;
  bestComposition: boolean;
  bestGroup: boolean;
  bestSolo: boolean;
  bestCandid: boolean;
  instagram: boolean;
}

// tags and reasoning are criteria-weighted summaries generated by rankPhotos.ts,
// distinct from the raw per-photo values in PhotoAnalysis.
export interface RankedPhoto {
  photo: PhotoFile;
  analysis: PhotoAnalysis;
  compositeScore: number;  // criteria-weighted score computed by rankPhotos.ts
  tags: string[];
  reasoning: string;
}

export interface ResultSection {
  key: string;
  title: string;
  photos: RankedPhoto[];
}

export interface RankedResults {
  sections: ResultSection[];
}
